removed start and wait for server steps in .yml

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -17,11 +17,11 @@ jobs:
               run: npm ci
             - name: Install Playwright Browsers
               run: npx playwright install --with-deps
-            - name: Start Server
-              run: npm run dev
-            - name: Wait for server
-              run: |
-                  while ! curl --output /dev/null --silent --fail http://127.0.0.1:5173; do sleep 1; done
+            # - name: Start Server
+            #   run: npm run dev
+            # - name: Wait for server
+            #   run: |
+            #       while ! curl --output /dev/null --silent --fail http://127.0.0.1:5173; do sleep 1; done
 
             # - name: Wait for server to start
             #   run: |
